// مجموعة إعدادات الوكلاء حسب كل مهمة
import { TaskCategory, TaskType } from '../types/types';
import { ANALYSIS_AGENT_CONFIG } from './analysisAgent';
import { CREATIVE_AGENT_CONFIG } from './creativeAgent';
import { INTEGRATED_AGENT_CONFIG } from './integratedAgent';
import { COMPLETION_AGENT_CONFIG } from './completionAgent';
import { RHYTHM_MAPPING_AGENT_CONFIG } from './rhythmMappingAgent';
import { CHARACTER_NETWORK_AGENT_CONFIG } from './characterNetworkAgent';
import { DIALOGUE_FORENSICS_AGENT_CONFIG } from './dialogueForensicsAgent';
import { THEMATIC_MINING_AGENT_CONFIG } from './thematicMiningAgent';
import { STYLE_FINGERPRINT_AGENT_CONFIG } from './styleFingerprintAgent';
import { CONFLICT_DYNAMICS_AGENT_CONFIG } from './conflictDynamicsAgent';
import { SCENE_GENERATOR_AGENT_CONFIG } from './sceneGeneratorAgent';
import { CHARACTER_VOICE_AGENT_CONFIG } from './characterVoiceAgent';
import { WORLD_BUILDER_AGENT_CONFIG } from './worldBuilderAgent';
import { PLOT_PREDICTOR_AGENT_CONFIG } from './plotPredictorAgent';
import { TENSION_OPTIMIZER_AGENT_CONFIG } from './tensionOptimizerAgent';
import { AUDIENCE_RESONANCE_AGENT_CONFIG } from './audienceResonanceAgent';
import { PLATFORM_ADAPTER_AGENT_CONFIG } from './platformAdapterAgent';
import { CHARACTER_DEEP_ANALYZER_AGENT_CONFIG } from './characterDeepAnalyzerAgent';
import { DIALOGUE_ADVANCED_ANALYZER_AGENT_CONFIG } from './dialogueAdvancedAnalyzerAgent';
import { VISUAL_CINEMATIC_ANALYZER_AGENT_CONFIG } from './visualCinematicAnalyzerAgent';
import { THEMES_MESSAGES_ANALYZER_AGENT_CONFIG } from './themesMessagesAnalyzerAgent';
import { CULTURAL_HISTORICAL_ANALYZER_AGENT_CONFIG } from './culturalHistoricalAnalyzerAgent';
import { PRODUCIBILITY_ANALYZER_AGENT_CONFIG } from './producibilityAnalyzerAgent';
import { TARGET_AUDIENCE_ANALYZER_AGENT_CONFIG } from './targetAudienceAnalyzerAgent';
import { LITERARY_QUALITY_ANALYZER_AGENT_CONFIG } from './literaryQualityAnalyzerAgent';
import { RECOMMENDATIONS_GENERATOR_AGENT_CONFIG } from './recommendationsGeneratorAgent';
import { ADAPTIVE_REWRITING_AGENT_CONFIG } from './adaptiveRewritingAgent';

export const AGENT_CONFIGS = Object.freeze<AIAgentConfig[]>([
  // === CORE FOUNDATIONAL AGENTS ===
  ANALYSIS_AGENT_CONFIG,
  CREATIVE_AGENT_CONFIG,
  INTEGRATED_AGENT_CONFIG,
  COMPLETION_AGENT_CONFIG,
  // === ADVANCED ANALYTICAL AGENTS ===
  RHYTHM_MAPPING_AGENT_CONFIG,
  CHARACTER_NETWORK_AGENT_CONFIG,
  DIALOGUE_FORENSICS_AGENT_CONFIG,
  THEMATIC_MINING_AGENT_CONFIG,
  STYLE_FINGERPRINT_AGENT_CONFIG,
  CONFLICT_DYNAMICS_AGENT_CONFIG,
  // === CREATIVE GENERATION AGENTS ===
  ADAPTIVE_REWRITING_AGENT_CONFIG,
  SCENE_GENERATOR_AGENT_CONFIG,
  CHARACTER_VOICE_AGENT_CONFIG,
  WORLD_BUILDER_AGENT_CONFIG,
  // === PREDICTIVE & OPTIMIZATION AGENTS ===
  PLOT_PREDICTOR_AGENT_CONFIG,
  TENSION_OPTIMIZER_AGENT_CONFIG,
  AUDIENCE_RESONANCE_AGENT_CONFIG,
  PLATFORM_ADAPTER_AGENT_CONFIG,
  // === ADVANCED SPECIALIZED MODULES ===
  CHARACTER_DEEP_ANALYZER_AGENT_CONFIG,
  DIALOGUE_ADVANCED_ANALYZER_AGENT_CONFIG,
  VISUAL_CINEMATIC_ANALYZER_AGENT_CONFIG,
  THEMES_MESSAGES_ANALYZER_AGENT_CONFIG,
  CULTURAL_HISTORICAL_ANALYZER_AGENT_CONFIG,
  PRODUCIBILITY_ANALYZER_AGENT_CONFIG,
  TARGET_AUDIENCE_ANALYZER_AGENT_CONFIG,
  LITERARY_QUALITY_ANALYZER_AGENT_CONFIG,
  RECOMMENDATIONS_GENERATOR_AGENT_CONFIG,
]);
